logger:
  enable: false
  pretty_backtrace: true
  level: debug
  format: compact

server:
  port: 5150
  host: http://localhost
  middlewares:
    limit_payload:
      body_limit: "12MB"

workers:
  mode: ForegroundBlocking

mailer:
  stub: true

database:
  uri: <%= get_env(name="DATABASE_URL", default="sqlite://storage/test.sqlite3?mode=rwc") %>
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: true
  dangerously_recreate: true

auth:
  jwt:
    secret: test-jwt-secret
    expiration: 604800
